# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 91juliansanchez
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: smile-centers-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: smile-centers-api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: any
          cors:  true
      - http:
          path: /{proxy+}
          method: any
          cors:  true
    environment:
      MONGODB_URI: ${env:MONGODB_URI}

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md
    - "node_modules/aws-sdk/**"
    - "node_modules/nest-cli/**"
    - "node_modules/@nestjs/cli/**"
    - "node_modules/typescript/**"
